const Test = [
      { 
        "id":"1",
        "roomid":"DEMO",
        "courseId":"666666",
        "courseName":'English for fun',
        "regular_starttime":"9:00",
        "regular_endtime":"12:00",
        "regular_weekday":"Monday",
        "description":"Hello world",
      },
      {
        "id":"2",
        "roomid":"M04",
        "courseId":"06016303",
        "courseName":'DISCRETE MATHEMATICS (2/2022) ',
        "regular_starttime":"12:00",
        "regular_endtime":"16:00",
        "regular_weekday":"Monday",
        "description":"Hello world",
      },
      {
        "id":"3",
        "roomid":"M21",
        "courseId":"06036320",
        "courseName":"COMPUTER SYSTEMS ORGANIZATION AND OPERATING SYSTEM (2/2022)",
        "regular_starttime":"9:00",
        "regular_endtime":"12:00",
        "regular_weekday":"Tuesday",
        "description":"Hello world",
      },
      {
        "id":"4",
        "roomid":"M22",
        "courseId":"06016315 ",
        "courseName":'COMPUTER PROGRAMMING (2/2022)',
        "regular_starttime":"12:00",
        "regular_endtime":"16:00",
        "regular_weekday":"Tuesday",
        "description":"Hello world",
      },
      {
        "id":"5",
        "roomid":"M23",
        "courseId":"06016311",
        "courseName":'MULTIMEDIA TECHNOLOGY (2/2022)',
        "regular_starttime":"9:00",
        "regular_endtime":"12:00",
        "regular_weekday":"Friday",
        "description":"Hello world",
      },
      {
        "id":"6",
        "roomid":"M24",
        "courseId":"06016302",
        "courseName":'MATHEMATICS FOR INFORMATION TECHNOLOGY (2/2022)',
        "regular_starttime":"8:30",
        "regular_endtime":"12:00",
        "regular_weekday":"Thursday",
        "description":"Hello world",
      },
      {
        "id":"7",
        "roomid":"LAB",
        "courseId":"06016330 ",
        "courseName":"PROJECT IN SOFTWARE ENGINEERING 2",
        "regular_starttime":"12:00",
        "regular_endtime":"15:00",
        "regular_weekday":"Wednesday",
        "description":"Hello world",
      },
      {
        "id":"8",
        "roomid":"LAB310",
        "courseId":"06016317",
        "courseName":"OBJECT-ORIENTED PROGRAMMING",
        "regular_starttime":"15:00",
        "regular_endtime":"18:00",
        "regular_weekday":"Wednesday",
        "description":"Hello world",
      },

]

const mockTest = [
    { 
      "id":"8",
      "roomid":"M04",
      "courseId":"5742",
      "courseName":"English for fun",
      "time":"13.00-14.00",
    },

]

export {Test, mockTest}