const TestStudents = [
    {   
        "name":"Siwakorn Pianmgam",
        "user_id":"62070180",
        "attendance":"Attend",
        "roomid":"LAB",
        "positionX":1,
        "positionY":2,
    },
    {
        "name":"Supakorn Kitiwattanakorn",
        "user_id":"62070183",
        "attendance":"Unregistered",
        "roomid":"M22",
        "positionX":0,
        "positionY":0,
    },    
    {   
        "name":"Chawanwit Sriumporn",
        "user_id":"62070044",
        "attendance":"Attend",
        "roomid":"M03",
        "positionX":0,
        "positionY":1,
    },
    {   
        "name":"Asama Klakarnkhai",
        "user_id":"62070220",
        "attendance":"Attend",
        "roomid":"M21",
        "positionX":0,
        "positionY":0,
    },
    {   
        "name":"Konthorn Supadilokluk",

        "user_id":"62070001",
        "attendance":"Unregistered",
        "roomid":"M04",
        "positionX":0,
        "positionY":0,
    },
    {
        "name":"SIRAPOP MANSAMAK",
        "user_id":"62070199",
        "attendance":"Attend",
        "roomid":"M03",
        "positionX":0,
        "positionY":0,
    },
    {
        "name":"Prakorn Kampao",
        "user_id":"62070115",
        "attendance":"Attend",
        "roomid":"M03",
        "positionX":1,
        "positionY":1,
    },
    {
        "name":"Siwakorn Somkanay",
        "user_id":"62070179",
        "attendance":"Unregistered",
        "roomid":"M03",
        "positionX":1,
        "positionY":1,
    },
    {
        "name":"Ukrit Sinrapachaisri",
        "user_id":"62070228",
        "attendance":"Attend",
        "roomid":"DEMO",
        "positionX":0,
        "positionY":0,
    },
    {
        "name":"Siwawong Wonglertchai",
        "user_id":"62070181",
        "attendance":"Attend",
        "roomid":"DEMO",
        "positionX":0,
        "positionY":0,
    },
    {
        "name":"Weatphom Mamak",
        "user_id":"62070173",
        "attendance":"Attend",
        "roomid":"DEMO",
        "positionX":0,
        "positionY":1,
    },
    {
        "name":"Piyanat Sangkuttiya",
        "user_id":"62070119",
        "attendance":"Attend",
        "roomid":"DEMO",
        "positionX":1,
        "positionY":0,
    },
    {
        "name":"Krittanut Siripornnoppakhunyanat",
        "user_id":"62070002",
        "attendance":"Attend",
        "roomid":"DEMO",
        "positionX":1,
        "positionY":0,
    },
    {
        "name":"Suparit Sgggggg",
        "user_id":"62070187",
        "attendance":"Attend",
        "roomid":"DEMO",
        "positionX":0,
        "positionY":0,
    },

]

const Testlogdata = [
    {   
        "name":"Siwakorn Pianmgam",

        "user_id":"62070180",
        "CheckInTime":"08.45",
        "CheckOutTime":"12.00",
        "roomid":"LAB",
        "attendance":"Attend",
        "positionX":1,
        "positionY":2,
    },
    {
        "name":"Supakorn Kitiwattanakorn",

        "user_id":"62070183",
        "CheckInTime":"09.00",
        "CheckOutTime":"12.00",
        "attendance":"Unregistered",
        "roomid":"M22",
        "positionX":0,
        "positionY":0,
    },    
    {   
        "name":"Chawanwit Sriumporn",

        "user_id":"62070044",
        "CheckInTime":"09.01",
        "CheckOutTime":"12.10",
        "roomid":"M03",
        "attendance":"Attend",
        "positionX":0,
        "positionY":1,
    },
    {   
        "name":"Asama Klakarnkhai",
        "user_id":"62070220",
        "CheckInTime":"08.30",
        "CheckOutTime":"12.10",
        "roomid":"M21",
        "attendance":"Attend",
        "positionX":0,
        "positionY":0,
    },
    {   
        "name":"Konthorn Supadilokluk",
        "user_id":"62070001",
        "CheckInTime":"08.50",
        "CheckOutTime":"12.10",
        "roomid":"M04",
        "attendance":"Unregistered",
        "positionX":0,
        "positionY":0,
    },
    {
        "name":"SIRAPOP MANSAMAK",
        "user_id":"62070199",
        "CheckInTime":"--.--",
        "CheckOutTime":"--.--",
        "roomid":"M03",
        "attendance":"Absent",
        "positionX":0,
        "positionY":0,
    },
    {
        "name":"Prakorn Kampao",
        "user_id":"62070115",
        "CheckInTime":"09.50",
        "CheckOutTime":"12.20",
        "roomid":"M03",
        "attendance":"Attend",
        "positionX":1,
        "positionY":1,    },
    {
        "name":"Siwakorn Somkanay",
        "user_id":"62070179",
        "CheckInTime":"09.00",
        "CheckOutTime":"12.00",
        "roomid":"M03",
        "attendance":"Unregistered",
        "positionX":1,
        "positionY":1,
    },
    {
        "name":"Ukrit Sinrapachaisri",
        "user_id":"62070228",
        "CheckInTime":"--.--",
        "CheckOutTime":"--.--",
        "roomid":"M21",
        "attendance":"Absent",
        "positionX":0,
        "positionY":0,
    },
    {

        "name":"Siwawong Wonglertchai",
        "user_id":"62070181",
        "CheckInTime":"09.00",
        "CheckOutTime":"12.00",
        "roomid":"M04",
        "attendance":"Attend",
        "positionX":0,
        "positionY":0,
    },
    {

        "name":"Weatphom Mamak",
        "user_id":"62070173",
        "CheckInTime":"--.--",
        "CheckOutTime":"--.--",
        "roomid":"M04",
        "attendance":"Absent",
        "positionX":0,
        "positionY":0,
    },
    {

        "name":"Piyanat Sangkuttiya",
        "user_id":"62070119",
        "CheckInTime":"08.45",
        "CheckOutTime":"12.00",
        "roomid":"M23",
        "attendance":"Attend",
        "positionX":0,
        "positionY":0,
    },
    {

        "name":"Krittanut Siripornnoppakhunyanat",
        "user_id":"62070002",
        "CheckInTime":"08.30",
        "CheckOutTime":"12.00",
        "roomid":"M24",
        "attendance":"Attend",
        "positionX":0,
        "positionY":0,
    },
    {
        "name":"Suparit Sgggggg",
        "user_id":"62070187",
        "CheckInTime":"13.00",
        "CheckOutTime":"14.00",
        "roomid":"DEMO",
        "attendance":"Attend",
        "positionX":0,
        "positionY":0,
    },

]


export {TestStudents, Testlogdata}